# Generated by Django 3.2.4 on 2021-06-14 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('medication_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('ppDosageInMg', models.IntegerField()),
                ('prescriptionNeeded', models.BooleanField()),
                ('inStock', models.BooleanField()),
                ('manufacturer', models.CharField(max_length=300)),
                ('imagePath', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('isChronic', models.BooleanField()),
                ('condition', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.doctors')),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionTypes',
            fields=[
                ('prescription_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('recurring', models.BooleanField()),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'prescription_types',
            },
        ),
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('redeemed', models.BooleanField()),
                ('validUntil', models.DateTimeField()),
                ('description', models.CharField(max_length=1000)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.doctors')),
                ('prescription_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.prescriptiontypes')),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='UserOwnsMedication',
            fields=[
                ('user_owns_medication_id', models.AutoField(primary_key=True, serialize=False)),
                ('boughtTime', models.DateTimeField()),
                ('remainingDosageInMg', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('medication_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.inventory')),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.patients')),
                ('prescription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.prescriptions')),
            ],
            options={
                'db_table': 'user_owns_medication',
                'unique_together': {('medication_id', 'patient_id')},
            },
        ),
    ]
