# Generated by Django 3.2.4 on 2021-06-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20210614_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='ppPrice',
            new_name='totalDosageInMg',
        ),
        migrations.AddField(
            model_name='inventory',
            name='totalPriceInEUR',
            field=models.IntegerField(default=(22.30)),
            preserve_default=False,
        ),
    ]
