# Generated by Django 3.2.4 on 2021-06-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20210614_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationTypes',
            fields=[
                ('medication_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'medication_types',
                'db_table': 'medication_types',
            },
        ),
    ]
