# Generated by Django 3.2.4 on 2021-06-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_inventory_medication_type_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userownsmedication',
            options={'verbose_name_plural': 'user_owns_medication'},
        ),
    ]
