# Generated by Django 3.2.4 on 2021-06-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_alter_userownsmedication_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userownsmedication',
            name='boughtTime',
            field=models.DateTimeField(null=True),
        ),
    ]
