# Generated by Django 3.2.4 on 2021-06-15 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_alter_userownsmedication_boughttime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserOwnsMedication',
            new_name='PatientOwnsMedication',
        ),
        migrations.AlterModelOptions(
            name='patientownsmedication',
            options={'verbose_name_plural': 'patient_owns_medication'},
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.patients'),
        ),
        migrations.AlterModelTable(
            name='patientownsmedication',
            table='patient_owns_medication',
        ),
    ]
