# Generated by Django 3.2.4 on 2021-06-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_auto_20210615_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptions',
            name='name',
            field=models.CharField(default='prescription_name_1', max_length=100),
            preserve_default=False,
        ),
    ]
