# Generated by Django 3.2.4 on 2021-06-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_prescriptions_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptions',
            name='status',
            field=models.CharField(default='accepted', max_length=20),
            preserve_default=False,
        ),
    ]
