# Generated by Django 3.2.4 on 2021-06-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_prescriptions_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptions',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
