# Generated by Django 3.2.4 on 2021-06-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0014_alter_inventory_totalpriceineur'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientownsmedication',
            name='totalDays',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
